const MenuData = [
  {
    id: 1,
    image: require('../assets/images/desserts/Colonel.jpg'),
    name: 'Spaghtti Bolonaise',
    category: 'Desserts',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 2,
    image: require('../assets/images/desserts/Dame blanche.jpg'),
    name: 'goie de Volaille',
    category: 'Desserts',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 3,
    image: require('../assets/images/desserts/la-dame-noire.jpg'),
    name: 'jareete de boeuf',
    category: 'Desserts',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 4,
    image: require('../assets/images/plat/Ailes de poulet au four.jpg'),
    name: 'Ailes de poulet au four',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 5,
    image: require('../assets/images/plat/Bouellete de baracuda provençale.jpeg'),
    name: 'Bouellete de baracuda provençale',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 6,
    image: require('../assets/images/plat/Bouillon de boulette de poisson.jpg'),
    name: 'Bouillon de boulette de poisson',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 7,
    image: require('../assets/images/plat/Boulette de boeuf sauce arachide.jpg'),
    name: 'Boulette de boeuf sauce arachide',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 8,
    image: require('../assets/images/plat/Boulette de poulet pate DArchide.jpg'),
    name: 'Boulette de poulet pate DArchide',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 9,
    image: require('../assets/images/plat/Boulette de viande sauce tomate.jpeg'),
    name: 'Boulette de viande sauce tomate',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 10,
    image: require('../assets/images/plat/Brochette de boeuf.jpg'),
    name: 'Brochette de boeuf',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 11,
    image: require('../assets/images/plat/Chevre télé jazz au champignon.jpeg'),
    name: 'Chevre télé jazz au champignon',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 12,
    image: require('../assets/images/plat/Coquelet au four.jpeg'),
    name: 'Coquelet au four',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 13,
    image: require('../assets/images/plat/Kedjienou.jpeg'),
    name: 'Kedjienou',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 14,
    image: require('../assets/images/plat/Lagneau au pois chiche.jpg'),
    name: 'Lagneau au pois chiche',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 15,
    image: require('../assets/images/plat/Pied de veau au curry.jpg'),
    name: 'Pied de veau au curry',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 16,
    image: require('../assets/images/plat/Pizza magarita.jpg'),
    name: 'Pizza magarita',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 17,
    image: require('../assets/images/plat/Pizza trois fromages .jpg'),
    name: 'Pizza trois fromages',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 18,
    image: require('../assets/images/plat/Poulet yassa avec du riz.jpg'),
    name: 'Poulet yassa avec du riz',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 19,
    image: require('../assets/images/plat/Riz au gras au poisson.jpg'),
    name: 'Riz au gras au poisson',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 20,
    image: require('../assets/images/plat/Saucisses libanaises.jpeg'),
    name: 'Saucisses libanaises',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 21,
    image: require('../assets/images/plat/Spaghtti Bolonaise.jpeg'),
    name: 'Spaghtti Bolonaise',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 22,
    image: require('../assets/images/plat/goie de Volaille.jpg'),
    name: 'goie de Volaille',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
  {
    id: 23,
    image: require('../assets/images/plat/jareete de boeuf.jpg'),
    name: 'jareete de boeuf',
    category: 'Plats',
    price: '$4.9',
    description: '2/3 espresso, 1/3 streamed milk',
  },
]

export default MenuData
